# Generated by Django 2.1.5 on 2019-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pass_id', models.CharField(max_length=14)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
